### ISSUE TITLE
RuntimeError: invalid argument 3: out of range 

### ISSUE THREAD

**Issue by hana9090** [Zhenye-Na/DA-RNN#13]
This is my data which I repaced in `../nasdaq/data.csv` directory.
I need to train model for price detection, this is how my data look like:
![image](https://user-images.githubusercontent.com/2920520/63651212-06b53100-c75b-11e9-8f5b-f3e8ec220668.png)

For CPU, I run the  `python3 main.py --lr 0.0001 --epochs 50`, but I got this error:

>   File "/content/drive/My Drive/Spot-Forcasting/paper-methods2019/DA-RNN/DA-RNN/src/model.py", line 77, in forward
>     x = torch.cat((h_n.repeat(self.input_size, 1, 1).permute(1, 0, 2),
> RuntimeError: invalid argument 3: out of range at /pytorch/aten/src/TH/generic/THTensor.cpp:392

![image](https://user-images.githubusercontent.com/2920520/63651232-3bc18380-c75b-11e9-8edc-3218f645347b.png)

Any idea how to solve it?
Thanks

**Comment by Zhenye-Na** [comment]
Hi @hana9090 , I just fixed the problem using GPU, please feel free to check out the newer version. I hope this also solved the CPU version.

If you have further new bugs or problems, please feel free to reach out to me here.

Thanks.
