### ISSUE TITLE
Dataframe has no attribute 'as_matrix' error

### ISSUE THREAD

**Issue by hanship0530** [Zhenye-Na/DA-RNN#19]
Hello, Zhenye-Na
I'm using pandas 0.25.1 version
I got error "Dataframe has no attribute 'as_matrix' "
I think as_matrix() to is changed to to_numpy() at new pandas version

**Comment by Zhenye-Na** [comment]
Hi, it has been a long time since I did not maintain this repo. If `as_matrix()` function does not work any longer, please feel free to make a pull request to fix this problem.

Thanks!

**Comment by n2535904** [comment]
yes you just change to:   to_numpy() for newer pandas coding convention.

**Comment by RuiRao** [comment]
> yes you just change to: to_numpy() for newer pandas coding convention.

thank you for your answer ,give me a big hands
#

**Comment by Zhenye-Na** [comment]
thanks to @dan-r95 , we have now fix the deprecation errors for this repo.

details, pls refer to https://github.com/Zhenye-Na/DA-RNN/pull/27

close this issue for now. thank you.
