### ISSUE TITLE
I encountered an issue where the input and tags did not match when I ran your code.

### ISSUE THREAD

**Issue by zwd2016** [Zhenye-Na/DA-RNN#2]
I need some help. This is error!
  File "F:/研究生资料/论文/注意力机制/DA-RNN-master-pytorch/DA-RNN-master/src/main.py", line 55, in <module>
    model.train()

  File "F:\研究生资料\论文\注意力机制\DA-RNN-master-pytorch\DA-RNN-master\src\model.py", line 285, in train
    loss = self.criterion(y_pred, y_true)

  File "G:\Users\ll\Anaconda3\envs\tensorflow_gpu\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)

  File "G:\Users\ll\Anaconda3\envs\tensorflow_gpu\lib\site-packages\torch\nn\modules\loss.py", line 372, in forward
    return F.mse_loss(input, target, size_average=self.size_average, reduce=self.reduce)

  File "G:\Users\ll\Anaconda3\envs\tensorflow_gpu\lib\site-packages\torch\nn\functional.py", line 1569, in mse_loss
    input, target, size_average, reduce)

  File "G:\Users\ll\Anaconda3\envs\tensorflow_gpu\lib\site-packages\torch\nn\functional.py", line 1537, in _pointwise_loss
    return lambd_optimized(input, target, size_average, reduce)

RuntimeError: input and target shapes do not match: input [128 x 1], target [128] at c:\users\administrator\downloads\new-builder\win-wheel\pytorch\aten\src\thnn\generic/MSECriterion.c:13

**Comment by zwd2016** [comment]
Thank you very much for your help. I am very concerned about this model and hope to understand the attention mechanism through this example. However, there are still problems like this:
F:\研究生资料\论文\注意力机制\DA-RNN-master-update\DA-RNN-master\src\model.py:145: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  x.view(-1, 2 * self.decoder_num_hidden + self.encoder_num_hidden)).view(-1, self.T - 1))
Traceback (most recent call last):

  File "<ipython-input-2-af403fb9053e>", line 1, in <module>
    runfile('F:/研究生资料/论文/注意力机制/DA-RNN-master-update/DA-RNN-master/src/main.py', wdir='F:/研究生资料/论文/注意力机制/DA-RNN-master-update/DA-RNN-master/src')

  File "G:\Users\ll\Anaconda3\envs\tensorflow_gpu\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "G:\Users\ll\Anaconda3\envs\tensorflow_gpu\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "F:/研究生资料/论文/注意力机制/DA-RNN-master-update/DA-RNN-master/src/main.py", line 55, in <module>
    model.train()

  File "F:\研究生资料\论文\注意力机制\DA-RNN-master-update\DA-RNN-master\src\model.py", line 261, in train
    self.iter_losses[epoch * iter_per_epoch + idx / self.batch_size] = loss

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
I know this problem may be because loss is a floating point number, and the index needs an integer. However, forcing conversion accuracy will lose too much. Like this : self.iter_losses[int(epoch * iter_per_epoch + idx / self.batch_size)] = loss  ?? (Such a setting can be work, but it runs very slowly. Is it necessary to set up the GPU to run this program?)

**Comment by Zhenye-Na** [comment]
I am pretty sure that you can add `CUDA()` support to this example to accelerate training, even parallel computing. However, my currently laptop does not support those things. I am afraid that I can not help adding these stuff for now.

Did you change any hyper-parameters? How many iterations did you run?

**Comment by zwd2016** [comment]
I have not changed any of the hyperparameters. The code is like this:
# Training parameters setting
parser.add_argument('--epochs', type=int, default=10, help='number of epochs to train [10, 200, 500]')
parser.add_argument('--resume', type=bool, default=False, help='resume training or not')
parser.add_argument('--lr', type=float, default=0.001, help='learning rate [0.001] reduced by 0.1 after each 10000 iterations')
parser.add_argument('--ngpu', type=int, default=0, help='number of GPUs to use')
parser.add_argument('--cuda', action='store_true', help='enables cuda')
### I added a statement like this, my laptop supports GPU, but I am not very sure how to set up to start GPU acceleration.
print (torch.cuda.is_available())
# Read dataset
X, y = read_data(opt.dataroot, debug=False)
# Initialize model
model = DA_rnn(X, y, opt.ntimestep, opt.nhidden_encoder, opt.nhidden_decoder, opt.batchsize, opt.lr, opt.epochs,opt.cuda)
The result is very strange：
Epochs:  0  Iterations:  222  Loss:  22775975.0631 and a Figure(but here not upload Figure)
This is my email:wendongz@hnu.edu.cn(Can we discuss this in Chinese using email?)

**Comment by zwd2016** [comment]
I epochs ten times when the Figure link is here:https://github.com/zwd2016/Figure-DA_RNN.As the value of the continuous training loss function is decreasing, it still looks huge. Is it the same for you to run this program?
Epochs:  0  Iterations:  222  Loss:  22833792.0631
Epochs:  10  Iterations:  2442  Loss:  17939488.9099
Epochs:  20  Iterations:  4662  Loss:  13794552.6982
Epochs:  30  Iterations:  6882  Loss:  10264205.3874

**Comment by Zhenye-Na** [comment]
Hi, sorry for the delay.

It is the same as mine, except that I just use a subset of the training data for sanity checking. According to your result, I think it is plausible.

**Comment by zwd2016** [comment]
Hello, thank you very much！

**Comment by Zhenye-Na** [comment]
Great. Since your problem is solved, I am gonna close this issue.

Thanks.
