### ISSUE TITLE
abut Eq 8

### ISSUE THREAD

**Issue by LittleTigger-alpha** [Zhenye-Na/DA-RNN#31]
I found that the Eq 8 in the paper is different from the coding function in your program. The tanh function is not used, but your decoding function is consistent with the paper, Thanks!!!!!

**Comment by MyraQERTdm** [comment]
> 
I also found this question. And the calculation method of attention in author's code is different from the thesis. 
Do you also study this thesis and try to repeat it? Would you like to discuss it with me?
