### ISSUE TITLE
main.py: error: unrecognized arguments: 

### ISSUE THREAD

**Issue by happy-wendy** [Zhenye-Na/DA-RNN#6]
hi~ i could not run the main.py,there is something wrong : from model import *
can you tell me how to solve it?
thank u ~
![image](https://user-images.githubusercontent.com/29154555/55144242-56c3a380-517b-11e9-8b6c-228b82164bbe.png)

**Comment by Zhenye-Na** [comment]
Sorry for the late reply. Have you solved this error yet?

I could not reproduce this error in my local environment. Would you like to replace `from model import *` with `from model import Encoder, Decoder, DA_rnn`?

Best,
Zhenye

**Comment by longwenxiu** [comment]
Thanks for your reply~

**Comment by Zhenye-Na** [comment]
Glad to hear that you solve the problem ^_^
