### ISSUE TITLE
one bug when running the code

### ISSUE THREAD

**Issue by Yavonqq** [Zhenye-Na/DA-RNN#9]
When I ran the code, there was a bug:''LSTM' object has no attribute 'flatten_parameters'',
Here is the code:
self.encoder_lstm.flatten_parameters()
_, final_stage = self.encoder_lstm(
    x_tilde.unsqueeze(0), (h_n, s_n))
    h_n = final_state[0]
    s_n = final_stage[1]

I am not sure if this bug happened due to the naming issue

**Comment by Zhenye-Na** [comment]
Problem solved. Please feel free to check it out.
